name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest

    environment: production

    env:
      PROD_DOMAIN: ${{ vars.PROD_DOMAIN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "Deploying to $PROD_DOMAIN"