jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      PROD_DOMAIN: ${{ vars.PROD_DOMAIN }}

    steps:
      - name: Deploy
        run: echo "Deploying to $PROD_DOMAIN"
